version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - CORS_ORIGIN=http://localhost:80

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend